version: '3'

services:
  python3:
    user: ${UID}:${GID}
    container_name: 'python3'
    restart: always
    build: .
    working_dir: /opt
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./opt:/opt
    ports:
      - '8888:8888'
    tty: true
